### PR TITLE
Ignore pino and plugins in stacktrace

### LINKED ISSUE #16: offsets is wrong when using with pino-debug
i'm using pino-debug along with pino-caller, changing the stack trace which is then printing the wrong line: 
```Error
    at eval (eval at asJson (/project/node_modules/pino-caller/index.js:16:5), <anonymous>:1:7)
    at Object.asJson (/project/node_modules/pino-caller/index.js:16:5)
    at Object.write (/project/node_modules/pino/lib/proto.js:140:28)
    at Object.LOG [as debug] (/project/node_modules/pino/lib/tools.js:37:26)
    at enabled (/project/node_modules/pino-debug/debug.js:19:16)
    at Object.<anonymous> (/project/packages/something/lib/index.js:12:16)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)```

will print `"Object.LOG [as debug] (/project/node_modules/pino/lib/tools.js:37:26)"`

It would be nice to be able to tweak the offsets.

### PR DESCRIPTION
**Pull request by phra**
will fix #16

### CODE REVIEW

**Comment by mcollina** [comment]
Thanks! Would you mind to add a test for this change?

File: index.js [hunk 1]
```diff
@@ -13,7 +13,7 @@ function traceCaller (pinoInstance) {
 
   function asJson (...args) {
     args[0] = args[0] || Object.create(null)
-    args[0].caller = Error().stack.split('\n')[STACKTRACE_OFFSET].substr(LINE_OFFSET)
+    args[0].caller = Error().stack.split('\n').filter(s => !s.includes('node_modules/pino'))[STACKTRACE_OFFSET].substr(LINE_OFFSET)
```
Comment (mcollina) [inline index.js]: pino might be a dependency of a dependency in some case. Also, I'm not sure if this would match paths on windows.

Comment (phra) [reply index.js]: > I'm not sure if this would match paths on windows.

i added a check for windows fs paths.

> pino might be a dependency of a dependency in some case

not really sure of what you mean, can you be more specific?
